services:
  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laptops
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    volumes:
      - mysql-laptops:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  mysql-laptops:
