version: '3.8'

services:
  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laptops
    volumes:
#      - ./db-scripts:/docker-entrypoint-initdb.d
      - mysql-data-laptops:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  mysql-data-laptops:
