server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/laptops?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect