version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laptops
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3336:3306"  # Host port 3336 mapped to container port 3306
    volumes:
      - db_data:/var/lib/mysql


  app1:
    image: lab2  # Replace with your app's Docker image name
    container_name: spring_app1

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/laptops  # Use the internal MySQL port 3306
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USERNAME: root
      NODE_ID: 1
      CLUSTER_PORTS: 8092,8093,8094,8095
      CLUSTER_ADDRESSES: spring_app1,spring_app2,spring_app3,spring_app4
    ports:
      - "8081:8081"
      - "8092:8092"

  app2:
    image: lab2  # Replace with your app's Docker image name
    container_name: spring_app2
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/laptops  # Use the internal MySQL port 3306
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USERNAME: root
      NODE_ID: 2
      CLUSTER_PORTS: 8092,8093,8094,8095
      CLUSTER_ADDRESSES: spring_app1,spring_app2,spring_app3,spring_app4
    ports:
      - "8082:8081"
      - "8093:8093"

  app3:
    image: lab2  # Replace with your app's Docker image name
    container_name: spring_app3
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/laptops  # Use the internal MySQL port 3306
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USERNAME: root
      NODE_ID: 3
      CLUSTER_PORTS: 8092,8093,8094,8095
      CLUSTER_ADDRESSES: spring_app1,spring_app2,spring_app3,spring_app4
    ports:
      - "8083:8081"
      - "8094:8094"

  app4:
    image: lab2  # Replace with your app's Docker image name
    container_name: spring_app4
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/laptops  # Use the internal MySQL port 3306
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USERNAME: root
      NODE_ID: 4
      CLUSTER_PORTS: 8092,8093,8094,8095
      CLUSTER_ADDRESSES: spring_app1,spring_app2,spring_app3,spring_app4
    ports:
      - "8084:8081"
      - "8095:8095"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
