version: '3.8'

services:
  app:
    image: lab3
    container_name: spring_app_lab3
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/laptops  # Use the internal MySQL port 3306
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USERNAME: root
    ports:
      - "8081:8081"
      - "9090:9090"